### PR TITLE
Edited "alien_copy.bmp" to transparent background with (same size 144 x 82)

### PR DESCRIPTION
**Pull request by akhileshthite**
### Here is the image

alien_copy

### CODE REVIEW

**Comment by imvisp** [comment]
> ### Here is the image
> 
> alien_copy
> 

Let me Check locally after I'll let you know.

**Comment by akhileshthite** [comment]
> > ### Here is the image
> > alien_copy
> 
> Let me Check locally after I'll let you know.

Okay, Thanks

**Comment by imvisp** [comment]
> > > ### Here is the image
> > > alien_copy
> > 
> > 
> > Let me Check locally after I'll let you know.
> 
> Okay, Thanks

cool it's work thank you for your contribution :+1:

**Comment by akhileshthite** [comment]
> > > > ### Here is the image
> > > > alien_copy
> > > 
> > > 
> > > Let me Check locally after I'll let you know.
> > 
> > 
> > Okay, Thanks
> 
> cool it's work thank you for your contribution 👍

Thank you :)

**Pull request merged**
